name: Run RSS Reader

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:       # Allows manual triggering of the workflow

jobs:
  run-rss-reader:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run RSS Reader Script
      run: |
        python rss_reader.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add feed_logs.xlsx data_lake/
        git commit -m 'Update feed logs and data lake files'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}